// <auto-generated />
using System;
using KooliProjekt.Application.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KooliProjekt.Application.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251123194901_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KooliProjekt.Application.Data.Asset", b =>
                {
                    b.Property<int>("AssetID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssetID"));

                    b.Property<int>("AssetClassID")
                        .HasColumnType("int");

                    b.Property<bool>("IsRealEstate")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ticker")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AssetID");

                    b.HasIndex("AssetClassID");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("KooliProjekt.Application.Data.AssetClass", b =>
                {
                    b.Property<int>("AssetClassID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssetClassID"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AssetClassID");

                    b.ToTable("AssetClasses");
                });

            modelBuilder.Entity("KooliProjekt.Application.Data.MonthlyHolding", b =>
                {
                    b.Property<int>("HoldingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HoldingID"));

                    b.Property<int>("AssetID")
                        .HasColumnType("int");

                    b.Property<int?>("MonthlyStateStateID")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StateID")
                        .HasColumnType("int");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("HoldingID");

                    b.HasIndex("AssetID");

                    b.HasIndex("MonthlyStateStateID");

                    b.ToTable("MonthlyHoldings");
                });

            modelBuilder.Entity("KooliProjekt.Application.Data.MonthlyState", b =>
                {
                    b.Property<int>("StateID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StateID"));

                    b.Property<decimal>("Deposits")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StateDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalPortfolioValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UninvestedCash")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Withdrawals")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("StateID");

                    b.ToTable("MonthlyStates");
                });

            modelBuilder.Entity("KooliProjekt.Application.Data.Asset", b =>
                {
                    b.HasOne("KooliProjekt.Application.Data.AssetClass", "AssetClass")
                        .WithMany()
                        .HasForeignKey("AssetClassID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssetClass");
                });

            modelBuilder.Entity("KooliProjekt.Application.Data.MonthlyHolding", b =>
                {
                    b.HasOne("KooliProjekt.Application.Data.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KooliProjekt.Application.Data.MonthlyState", "MonthlyState")
                        .WithMany()
                        .HasForeignKey("MonthlyStateStateID");

                    b.Navigation("Asset");

                    b.Navigation("MonthlyState");
                });
#pragma warning restore 612, 618
        }
    }
}
